from core.nlp_utils import preprocess, detect_intent


def answer_question(mode, question, df, stats, insights=None):
    clean_q = preprocess(question)
    intent = detect_intent(clean_q)

    # -------- SALES MODE --------
    if mode == "sales":
        if intent == "sales_drop":
            return (
                "Sales declines are observed where consecutive periods show reduced sales values. "
                "Such drops often indicate weaker demand or external constraints. "
                "This insight is based on historical sales trends only."
            )

        if intent == "sales_growth":
            return (
                "Sales growth periods indicate increased demand or improved performance. "
                "Consistent upward trends suggest positive momentum."
            )

        if intent == "best_performance":
            best = df["Sales"].max() if "Sales" in df.columns else None
            return (
                f"The highest sales value observed is {best:.0f}. "
                "This represents the strongest performing period in the dataset."
            )

        if intent == "average":
            avg = stats["mean"].get("Sales", 0)
            return (
                f"The average sales value is approximately {avg:.2f}. "
                "This provides a baseline for performance comparison."
            )

        return (
            "I understand your question, but it does not map clearly to a supported sales insight. "
            "Try asking about sales drops, growth, best performance, or averages."
        )

    # -------- STOCK MODE --------
    if mode == "stocks":
        if intent == "profit_loss":
            pl = insights.get("total_profit_loss", 0)
            return (
                f"The total profit or loss across your portfolio is {pl:.2f}. "
                "Positive values indicate profit, while negative values indicate loss."
            )

        if intent == "risk":
            vol = insights.get("volatility", 0)
            return (
                f"The portfolio volatility is approximately {vol:.2f}. "
                "Higher volatility implies higher risk."
            )

        if intent == "return":
            ret = insights.get("average_return_percent", 0)
            return (
                f"The average return across holdings is {ret:.2f}%. "
                "Returns are calculated using buy vs current prices."
            )

        return (
            "I could not confidently match your question to a stock-related insight. "
            "Try asking about profit, loss, risk, or returns."
        )

    # -------- PREDICTION MODE --------
    if mode == "prediction":
        if intent == "forecast_confidence":
            return (
                "Forecasts generated by this system are probabilistic and not guaranteed. "
                "They rely on historical patterns and scenario assumptions."
            )

        if intent == "forecast_scenario":
            return (
                "Optimistic and pessimistic scenarios represent possible upper and lower bounds. "
                "They help assess risk, not predict exact outcomes."
            )

        return (
            "Prediction questions should focus on trends, scenarios, or uncertainty. "
            "Exact future values cannot be guaranteed."
        )

    return "Unable to interpret the question in the current context."
